services:
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=9091
    ports:
      - "9091:9091"
    depends_on: 
      - keycloak
   
  blazor.client:
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=9092
     ports:
      - "9092:9092"
     depends_on: 
      - webapi

  keycloak.database:
    environment:
       POSTGRES_DB: $KC_DB
       POSTGRES_USER: $KC_DB_USERNAME
       POSTGRES_PASSWORD: $KC_DB_PASSWORD
    volumes:
      - ./.containers/keycloak_db:/var/lib/postgresql/data
    ports:
      - "9093:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  keycloak:
    environment: 
      KEYCLOAK_ADMIN: $KEYCLOAK_ADMIN
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      KC_HTTP_PORT: 9096
      KC_DB: $KC_VENDOR
      KC_DB_USERNAME: $KC_DB_USERNAME
      KC_DB_PASSWORD: $KC_DB_PASSWORD
      KC_HOSTNAME: keycloak
      KC_DB_URL_HOST: keycloak.database
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: $KC_DB
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_PROXY: edge
      PROXY_ADDRESS_FORWARDING: true
    ports:
      - "8443:8443"
      - "9095:9000"
      - "9096:9096"
    depends_on: 
      - keycloak.database
    command: start-dev